# Generated by Django 5.0.2 on 2024-03-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genero_terror',
            new_name='subgeneros',
        ),
    ]
